lib/site-inspector/dns.rb
Follow up to https://github.com/benbalter/site-inspector-ruby/pull/14, fix for DNSEC tests.
@konklone for context, ran into the same problem with IPV6. Not all DNS servers respond with the same fields when you request ANY. Depending on the server, it may not return `AAAA` or `DNSKEY` records unless explicitly asked. Although a bit slower (another DNS lookup call), this should be compatible with more DNS servers.
Alternatively, we could try to hard code a specific server (e.g., Google), but think this is less fragile.
=> Fix for dnssec

lib/site-inspector/headers.rb
Downcase the keys in the header hash before running any check, and just use that hash for sanity.
@konklone any reason we couldn't do this?
=> Refactor headers a bit

bin/site-inspector, lib/site-inspector.rb, site-inspector.gemspec, test/test_site_inspector_bin.rb
The contents of the headers are helpful information, especially for finer grained analysis than site-inspector builds in itself. This adds a `headers` field to the JSON output of the CLI interface.
I noticed when using this that `JSON.pretty_generate`, which ships with the Ruby stdlib, chokes on Unicode characters. Some Arizonan domains have an `X-Header` header with a value of `Boost Helás Avril 1.0`, and that was causing crashes.
The problem seemed internal to the JSON stdlib, and not something I could fix by encoding the data before sending in, so this switches to Oj. Oj is my favorite JSON encoder/decoder, is insanely fast, and fixes the Unicode issue.
=> Expose headers in CLI output, and switch to Oj for JSON encoding

lib/site-inspector.rb, lib/site-inspector/cache.rb
This allows the caller to specify a `CACHE` environment variable that points to a directory. If specified, Typheous will use a disk cache that will persist across individual executions of `site-inspector`.
This drastically speeds up repeated and batch use of `site-inspector`.
=> Adds a basic disk cache

lib/site-inspector/cache.rb
If a cache file was left in a corrupted state (which causes an `ArgumentError` during unmarshal) then detect it, delete it, and move on as if it was uncached.
=> Be resilient to corrupted cache files

lib/site-inspector.rb, lib/site-inspector/cache.rb
By setting `$CACHE_REPLACE` to anything, it causes the cache for any accessed domain to be ignored, deleted, and replaced with the subsequent results.
This is meant to be an easy way to invalidate the cache for a particular domain name, without needing to bend over backwards to figure out which hash-named file in the cache corresponds to individual HTTP requests.
=> Adds a quick cache replacement function

lib/site-inspector/checks/headers.rb, lib/site-inspector/domain.rb, spec/checks/site_inspector_endpoint_headers_spec.rb
We know most API calls to the domain model are going to require That the root of all four endpoints are called. Rather than process them In serial, lets grab them in parallel and cache the results to speed up later calls.
=> Prefetch all endpoints prior to calculating to_h

lib/site-inspector/checks/headers.rb
Remove duplicate key for :click_jacking_protection. Existing code was throwing a warning.
=> Update headers.rb, fixes warning

.gitignore, lib/site-inspector/disk_cache.rb, spec/site_inspector_disk_cache_spec.rb
The memory cache can use a `Typhoeus::Request` object itself as the hash key, but the disk cache has to name files with a simple string. The disk cache was doing this by building the cache path from the request object's `cache_key`, but it somehow got dropped in https://github.com/benbalter/site-inspector/commit/cbd847ef9f858cf010d1f9a1bd74a62c07fb768d during the 2.0 refactor. This caused site-inspector to break when the disk cache was used.
I've also `.gitignore`'d the use of a `/cache` directory in the project root, as a convenience for debug/development.
=> Fix disk cache

lib/site-inspector/domain.rb
Hash key copy editor reporting for duty.
Small as it is, since this is a dict/JSON key typo, this is technically a backwards-incompatible change. I'm not sure whether it's worth sticking with strict semver and bumping to 3.0, if 2.0's not in much use in the wild.
I think that as I dive into the site-inspector refactor from 1.0.2 -> 2.0.0, I'm likely to suggest further backwards-incompatible changes. I'm submitting this as a PR to a `2.1` branch, not to `master`, to offer the opportunity to grapple with them all at once.
That said, I know large-scale non-incremental refactors are a software engineering nightmare. So if you'd like to push this directly to `master` and go from there, :+1: too.
=> Fix "canoncial" typo

.gitignore, .travis.yml, lib/site-inspector/checks/accessibility.rb, package.json, script/bootstrap, script/cibuild, spec/checks/site_inspector_endpoint_accessibility_spec.rb
@adelevie this is a pull request against #39, implementing some of the things I suggestion on the line-by-line, plus a few tweaks I found once in the code. Specifically:
* Add a `package.json` file to make installing and versioning Pa11y in development and test a bit easier
* Move the standards to a class constant
* Move the individual checks to a magic method to DRY things up
* Simplify how we shell out to Pa11y and respect it's exit code
* Guard against invalid standards
* Added a `standard?` method
* Check for Pa11y existence via `pa11y --version` so we know it actually executes
* Made things a bit more object-oriented and deterministic
* The accessibility object now has `level` and `standard` getters and setters, defaulting to `508` and `error`.
* This allows us to expose a `valid?` …
=> Accessibility check tweaks

lib/site-inspector/domain.rb, lib/site-inspector/endpoint.rb, spec/site_inspector_domain_spec.rb, spec/site_inspector_endpoint_spec.rb
In site-inspector 1.X, "live" meant a 2XX response code. It would mean `!!response`, where `response` would be truthy if `response.success?` was true, and `false` if the response was nil or failed.
In 1.0.2, I added "up", which meant: "Is this domain/endpoint reachable over HTTP at all?" Even an endpoint that returned a 500 response code was "up" in the sense that the site responded to connections.
There are various cases where it's valuable to measure whether a domain responds to HTTP at all, and to distinguish an unreachable endpoint from an endpoint which just has a [404 page lying around](https://www.nist.gov/).
In 2.0, "live" got renamed to "up", which changed the intended meaning of "up". This pull request separates their definitions again:
```ruby
def live?
response && …
```
=> Restore the difference between "live" and "up"

lib/site-inspector/checks/accessibility.rb, lib/site-inspector/checks/check.rb, lib/site-inspector/endpoint.rb, spec/checks/site_inspector_endpoint_check_spec.rb
This prevents the pa11y check from running by default when pa11y isn't installed.
=> Only run "enabled" checks

lib/site-inspector/checks/accessibility.rb, lib/site-inspector/checks/check.rb, lib/site-inspector/endpoint.rb, spec/checks/site_inspector_endpoint_accessibility_spec.rb, spec/checks/site_inspector_endpoint_check_spec.rb
Because if, e.g. pa11y is installed or not, shouldn't be an instance-level question.
=> Move enabled? to the class

lib/site-inspector.rb, lib/site-inspector/checks/headers.rb, lib/site-inspector/checks/sniffer.rb, spec/checks/site_inspector_endpoint_sniffer_spec.rb
This pull request does a few things:
1. `Sniffer#cms` is now `Sniffer#framework` to be more inclusive
2. `Sniffer#framework` returns a symbol, not a hash
3. `Sniffer#framework` now detects PHP and Expression Engine (if no CMS is detected)
4. `Headers#cookies` now properly parses the raw cookie headers as sent from the server
=> Better framework sniffing

lib/site-inspector.rb, lib/site-inspector/checks/cookies.rb, lib/site-inspector/checks/headers.rb, lib/site-inspector/checks/sniffer.rb, spec/checks/site_inspector_endpoint_cookies_spec.rb, spec/checks/site_inspector_endpoint_headers_spec.rb, spec/checks/site_inspector_endpoint_sniffer_spec.rb, spec/site_inspector_endpoint_spec.rb
This creates a dedicated cookie check, that actually parses out cookies using Ruby's native cookie handling and can return individual cookies or check for things like secure cookies.
It pulls the various cookie functions from various places into one class.
=> Better cookie handling

lib/site-inspector/checks/sniffer.rb, spec/checks/site_inspector_endpoint_sniffer_spec.rb
Exposes `Sniffer#open_source?`
=> Detect if a website is using an open source framework

lib/site-inspector.rb, lib/site-inspector/endpoint.rb, site-inspector.gemspec
Fixes #65.
This roughly cuts the time to crawl a site in half and required some changes to how we memoize our Hydra instance in order to make it thread safe. TL;DR: `Typhoeus::Hydra.hyrdra` is thread safe, while `Typhoeus::Hydra.new` is not.
/cc https://github.com/oscardelben/firebase-ruby/issues/15, https://github.com/typhoeus/ethon/issues/85, https://github.com/typhoeus/ethon/issues/96
=> Make checks thread safe, parallelize checks

lib/site-inspector.rb, lib/site-inspector/checks/content.rb, spec/checks/site_inspector_endpoint_accessibility_spec.rb, spec/checks/site_inspector_endpoint_check_spec.rb, spec/checks/site_inspector_endpoint_content_spec.rb, spec/checks/site_inspector_endpoint_cookies_spec.rb, spec/checks/site_inspector_endpoint_dns_spec.rb, spec/checks/site_inspector_endpoint_headers_spec.rb, spec/checks/site_inspector_endpoint_hsts_spec.rb, spec/checks/site_inspector_endpoint_https_spec.rb, spec/checks/site_inspector_endpoint_sniffer_spec.rb, spec/site_inspector_domain_spec.rb, spec/site_inspector_endpoint_spec.rb, spec/site_inspector_spec.rb
This pull requests moves the default HTTP verb from `GET` to `HEAD` to attempt to speed things up.
The only check that actually looks at the response body is the Content check. Checking, if, e.g., an endpoint responds, or what headers it returns, can be accomplished with a `HEAD` request, which, per the spec, should be identical to a `GET` request, just without the response body.
=> Prefer HEAD requsets

lib/site-inspector.rb, lib/site-inspector/domain.rb, lib/site-inspector/endpoint.rb, script/console, spec/site_inspector_domain_spec.rb, spec/site_inspector_endpoint_spec.rb
Changes:
* Add debug mode via `DEBUG` config var which forces Typhoeus and Ethon into verbose output mode
* Prefetch endpoints (in parallel) before calculating a canonical endpoint
* Pass domain object to endpoint to facilitating caching when one endpoint redirects to another
* Calls to the root of an endpoint now have an explicit trailing slash to facilitate caching and prevent redirects
* `resolves_to` now makes a `HEAD` request to the redirected URL, which could be potentially cached, if an internal redirect, and only makes a follow location request if the `HEAD` request returns a `30x` response code.
Fixes #72.
=> WIP: Reduce the number of net calls made per check

lib/site-inspector.rb
I need to use an http proxy so I need to override the typhoeus options.  Please let me know if there is a better way to accomplish this...
=> allow overridable options
